cxx_binary(
  name = 'test',
  header_namespace = '',
  headers = glob([
    '*.h',
    '*.hpp',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  compiler_flags = [
    '-std=c++11',
  ],
  deps = [
    '//:any-lite',
  ],
)
